import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillInstagram, AiFillYoutube } from "react-icons/ai";
import { WiDaySunnyOvercast } from "react-icons/wi";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sonny Luu - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Developed by Sonny</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-89999999999999999999999999999999999999999999999999999999999992xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Sonny Luu
            </h2>
            <h3 className="text-2xl py-2">Developer and designer.</h3>
            <p className="text-md py-5 text-gray-800">
              Currently working as a front-end developer at{" "}
              <span className="text-teal-500">Capgemini</span> Financial
              Services.
            </p>
          </div>
          <div className="text-4xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillInstagram />
            <WiDaySunnyOvercast />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">About me</h3>
            <p className="text-md py-2 text-gray-800">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex non
              dolorem recusandae voluptates veritatis quaerat sint sequi,
              dolorum error reprehenderit. Ab qui repudiandae corrupti sit
              dolorum ducimus nobis maiores adipisci.
            </p>
            <p className="text-md py-2 text-gray-800">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex non
              dolorem recusandae voluptates veritatis quaerat sint sequi,
              dolorum error reprehenderit. Ab qui repudiandae corrupti sit
              dolorum ducimus nobis maiores adipisci.
            </p>
            <p className="text-md py-2 text-gray-800">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex non
              dolorem recusandae voluptates veritatis quaerat sint sequi,
              dolorum error reprehenderit. Ab qui repudiandae corrupti sit
              dolorum ducimus nobis maiores adipisci.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
